#!/usr/bin/env python3
"""Regenerate the web logo assets from the designer's vector master.

MuPDF's own SVG writer is used rather than re-assembling the bezier items by
hand: the "e" counter starts exactly where the previous subpath ends, so a
hand-rolled reconstruction cannot tell the subpaths apart and fills the glyph
in solid. Cropping is done purely by swapping the viewBox.
"""
import re
import sys
from pathlib import Path

import fitz
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
DEFAULT_SRC = Path.home() / "Desktop/03_CoColour Life/cocolour branding rev4/Logo Sourcefile/Logo Sourcefile.pdf"

# Measured from the rev 4 master (2026-08-22). Its ArtBox and the ink bbox of
# page 1 agree exactly, and unlike the earlier master it carries no hidden
# circles, so the drawing bbox is taken as-is. The mark is 41 circles.
FULL = (176.5360, 403.8279, 646.9281, 192.3438)   # mark + wordmark
MARK = (176.5360, 403.8279, 197.8292, 192.3438)   # mark only

NAVY = "#1b1464"   # the wordmark's ink; no circle uses it, so it isolates glyphs

BANNER = ("<!-- Generated by tools/build_logo.py from the designer's vector master\n"
          "     (Logo Sourcefile.pdf, {what}). Do not hand-edit, recolour, redraw\n"
          "     or re-space this file — regenerate it instead.\n"
          "     Ink #1B1464, accent #BB002D. -->\n")


def page_svg(src):
    return fitz.open(str(src))[0].get_svg_image(text_as_path=True)


def crop(svg, box, drop_wordmark=False, title=None, what=""):
    x, y, w, h = box
    out = svg.replace('width="1000" height="1000" viewBox="0 0 1000 1000"',
                      f'viewBox="{x} {y} {w} {h}"', 1)
    if drop_wordmark:
        out = re.sub(r'<path[^>]*fill="' + NAVY + r'"[^>]*/>\s*', "", out)
    if title:
        out = out.replace("<defs>", f"<title>{title}</title>\n<defs>", 1)
        out = out.replace("<svg ", '<svg role="img" aria-label="CoColour Life" ', 1)
    else:
        out = out.replace("<svg ", '<svg role="presentation" ', 1)
    # normalise MuPDF's lowercase hex so the files read like the brand book
    out = re.sub(r'fill="#([0-9a-f]{6})"', lambda m: 'fill="#%s"' % m.group(1).upper(), out)
    return BANNER.format(what=what) + out


def rasterise(svg_path, width_px):
    page = fitz.open(str(svg_path))[0]
    factor = width_px / page.rect.width
    pix = page.get_pixmap(matrix=fitz.Matrix(factor, factor), alpha=True)
    return Image.frombytes("RGBA", (pix.width, pix.height), pix.samples)


def main():
    # No favicon here: rev 4 ships its own .ico, a simplified 8-dot mark drawn
    # for 16-48px where the full 41-dot mark is illegible. assets/favicon.ico
    # holds the designer's rasters verbatim and is not generated from this master.
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.exists():
        sys.exit(f"master artwork not found: {src}\npass its path as the first argument")

    svg = page_svg(src)
    (ASSETS / "logo.svg").write_text(
        crop(svg, FULL, title="CoColour Life", what="page 1, colour horizontal lockup"))
    (ASSETS / "logo-mark.svg").write_text(
        crop(svg, MARK, drop_wordmark=True, title="CoColour Life", what="page 1, symbol only"))

    # logo.png — 1400px wide artwork on a 24px transparent margin
    art = rasterise(ASSETS / "logo.svg", 1400 - 48)
    canvas = Image.new("RGBA", (1400, art.height + 48), (0, 0, 0, 0))
    canvas.paste(art, (24, 24), art)
    canvas.save(ASSETS / "logo.png")

    # logo-mark.png — 512 square, mark centred (it is 1.0285:1, not square)
    mark = rasterise(ASSETS / "logo-mark.svg", 512)
    square = Image.new("RGBA", (512, 512), (0, 0, 0, 0))
    square.paste(mark, (0, (512 - mark.height) // 2), mark)
    square.save(ASSETS / "logo-mark.png")

    # apple-touch-icon — 180 square, white ground, 16px inset (iOS does not
    # composite transparency, it puts the icon on black)
    inner = rasterise(ASSETS / "logo-mark.svg", 180 - 32)
    icon = Image.new("RGBA", (180, 180), (255, 255, 255, 255))
    icon.paste(inner, (16, (180 - inner.height) // 2), inner)
    icon.convert("RGB").save(ASSETS / "apple-touch-icon.png")

    for name in ("logo.svg", "logo-mark.svg",
                 "logo.png", "logo-mark.png", "apple-touch-icon.png"):
        print(f"wrote assets/{name} ({(ASSETS / name).stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
